// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/settings-toggles/ToggleStates.tsx": () => import("../components/mockups/settings-toggles/ToggleStates.tsx")
};
